# docker-compose.yml
services:
  remark42:
    image: ghcr.io/umputun/remark42:latest
    container_name: remark42
    restart: unless-stopped
    # Don't expose port directly anymore
    expose:
      - '8080'
    environment:
      - SITE=remark
      - REMARK_URL=https://deb5ead704b5.ngrok-free.app # Your actual blog URL
      - SECRET=dev_secret_change_me_in_production
      - ALLOWED_HOSTS=localhost,127.0.0.1,localhost:3000,deb5ead704b5.ngrok-free.app
      - ALLOWED_ORIGINS=http://localhost:3000,https://localhost:3000,http://127.0.0.1:3000,https://127.0.0.1:3000,https://deb5ead704b5.ngrok-free.app
      - AUTH_ANON=true
      - ANONYMOUS_VOTE=true
      - CORS_ENABLED=true
      - ADMIN_SHARED_ID=admin
      - ADMIN_SHARED_EMAIL=admin@localhost
      - CSP_ENABLED=false
      - CSP=false  
      - X_FRAME_OPTIONS=ALLOWALL
      - FRAME_OPTIONS=
      - CONTENT_SECURITY_POLICY=
      - AUTH_SAME_SITE=none
      - SESSION_ONLY=false
      - SECURE=false
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - DBUG=true
    volumes:
      - ./remark42-data:/srv/var

  nginx:
    image: nginx:alpine
    container_name: remark42-proxy
    restart: unless-stopped
    ports:
      - '8081:8081'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - remark42
