# docker-compose.yml
services:
  remark42:
    image: ghcr.io/umputun/remark42:latest
    container_name: remark42
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - SITE=remark
      - REMARK_URL=https://61faf433f3de.ngrok-free.app  # Your ngrok URL
      - SECRET=dev_secret_change_me_in_production
      - ALLOWED_HOSTS=localhost,127.0.0.1,61faf433f3de.ngrok-free.app
      - ALLOWED_ORIGINS=http://localhost:3000,https://localhost:3000
      - AUTH_ANON=true
      - CORS_ENABLED=true
    volumes:
      - ./remark42-data:/srv/var